#!/bin/bash
# GitHub Push Commands - Copy and Run These Commands

echo "🚀 Login Portal - GitHub Push Instructions"
echo "=========================================="
echo ""
echo "Follow these exact steps to push your code to GitHub:"
echo ""

# Step 1
echo "STEP 1: Create a repository on GitHub"
echo "======================================"
echo "1. Go to https://github.com/new"
echo "2. Repository name: LoginPortal"
echo "3. Description: Full-stack login portal with CI/CD deployment"
echo "4. Choose: Public (for public access) or Private (for private access)"
echo "5. DO NOT initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "After creating, you'll see instructions like:"
echo "  git remote add origin https://github.com/itsdikshitaa/LoginPortal.git"
echo ""
echo "---"
echo ""

# Step 2
echo "STEP 2: Run these commands in your project directory"
echo "======================================================"
echo ""
echo "# Navigate to project directory"
echo "cd C:\\Users\\diksh\\OneDrive\\Documents\\GitHub\\LoginPortal"
echo ""
echo "# Configure Git (if not already done)"
echo "git config user.name \"Your Name\""
echo "git config user.email \"your-email@example.com\""
echo ""
echo "# Add your GitHub repository as remote"
echo "git remote add origin https://github.com/itsdikshitaa/LoginPortal.git"
echo ""
echo "# Verify the remote"
echo "git remote -v"
echo ""
echo "# Set branch to main and push"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "---"
echo ""

# Step 3
echo "STEP 3: Verify on GitHub"
echo "======================="
echo "1. Go to https://github.com/itsdikshitaa/LoginPortal"
echo "2. You should see all your files"
echo "3. You should see the git history/commits"
echo "4. .gitignore is working if node_modules is NOT listed"
echo ""
echo "---"
echo ""

# Step 4
echo "STEP 4: Setup GitHub Webhook (for Jenkins)"
echo "=========================================="
echo "1. Go to https://github.com/itsdikshitaa/LoginPortal/settings/hooks"
echo "2. Click 'Add webhook'"
echo "3. Configure:"
echo "   - Payload URL: http://YOUR_JENKINS_IP:8080/github-webhook/"
echo "   - Content type: application/json"
echo "   - Events: Just the push event"
echo "   - Active: Checked ✓"
echo "4. Click 'Add webhook'"
echo ""
echo "---"
echo ""

# COPY-PASTE READY COMMANDS
echo "📋 COPY & PASTE READY - Commands to Run"
echo "========================================"
echo ""
echo "# If remote doesn't exist:"
echo "git remote add origin https://github.com/itsdikshitaa/LoginPortal.git"
echo ""
echo "# Set main branch and push:"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# First time might ask for credentials:"
echo "# - Username: YOUR_GITHUB_USERNAME"
echo "# - Password: YOUR_GITHUB_PERSONAL_ACCESS_TOKEN (not password!)"
echo ""
echo "---"
echo ""

# Alternative for SSH
echo "🔒 ALTERNATIVE - If Using SSH Keys"
echo "=================================="
echo ""
echo "# Add SSH remote (instead of HTTPS):"
echo "git remote set-url origin git@github.com:itsdikshitaa/LoginPortal.git"
echo ""
echo "# Push to GitHub:"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "---"
echo ""

# GitHub Token Setup
echo "🔑 Generate GitHub Personal Access Token"
echo "======================================="
echo ""
echo "If you need to use HTTPS instead of SSH:"
echo ""
echo "1. Go to https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Token name: LoginPortal-Push"
echo "4. Expiration: 90 days"
echo "5. Select scopes:"
echo "   ✓ repo (all)"
echo "   ✓ workflow"
echo "6. Generate token"
echo "7. Copy token (shown only once!)"
echo "8. Use as password when pushing"
echo ""
echo "---"
echo ""

# Troubleshooting
echo "❌ Troubleshooting"
echo "================="
echo ""
echo "Q: 'fatal: remote origin already exists'"
echo "A: git remote remove origin"
echo "   git remote add origin https://github.com/itsdikshitaa/LoginPortal.git"
echo ""
echo "Q: 'permission denied' or '403 error'"
echo "A: Use GitHub Personal Access Token as password (not your GitHub password)"
echo ""
echo "Q: 'refusing to merge unrelated histories'"
echo "A: git pull --allow-unrelated-histories"
echo "   git push -u origin main"
echo ""
echo "Q: 'Could not read Username'"
echo "A: git config --global user.name \"Your Name\""
echo "   git config --global user.email \"your-email@example.com\""
echo ""
echo "---"
echo ""

# Verification
echo "✅ After Pushing - Verify Everything"
echo "===================================="
echo ""
echo "1. Check files on GitHub:"
echo "   https://github.com/itsdikshitaa/LoginPortal"
echo ""
echo "2. Verify all files are there:"
echo "   - views/ folder with 7 .ejs files ✓"
echo "   - config/db.js ✓"
echo "   - controllers/authController.js ✓"
echo "   - middleware/auth.js ✓"
echo "   - models/User.js ✓"
echo "   - routes/auth.js ✓"
echo "   - public/css/style.css ✓"
echo "   - public/js/validation.js ✓"
echo "   - server.js ✓"
echo "   - package.json ✓"
echo "   - Jenkinsfile ✓"
echo "   - README.md ✓"
echo "   - All markdown docs ✓"
echo ""
echo "3. Check git log:"
echo "   git log"
echo "   Should show 3 commits"
echo ""
echo "---"
echo ""

# Next Steps
echo "🎯 Next Steps After GitHub Push"
echo "==============================="
echo ""
echo "1. AWS EC2 Setup"
echo "   - Read: AWS-EC2-SETUP.md"
echo "   - Time: 20-30 minutes"
echo ""
echo "2. Jenkins Setup"
echo "   - Read: GITHUB-JENKINS-SETUP.md"
echo "   - Time: 15-20 minutes"
echo ""
echo "3. Test Pipeline"
echo "   - Make a change locally"
echo "   - git push to GitHub"
echo "   - Jenkins automatically builds and deploys"
echo ""
echo "4. Verify Deployment"
echo "   - Visit http://your-ec2-ip:5000"
echo "   - Test signup, login, logout"
echo ""
echo "---"
echo ""

echo "✨ You're Ready to Deploy!"
echo "========================="
echo ""
echo "Questions? Check these files:"
echo "- QUICK-START.md - 5-step setup guide"
echo "- AWS-EC2-SETUP.md - EC2 deployment"
echo "- GITHUB-JENKINS-SETUP.md - CI/CD setup"
echo "- README.md - General information"
echo ""
echo "Good luck! 🚀"
echo ""
